emporio/core/urls.py
from django.urls import path
from .views import home, aboutUs, carrito, formulario_ingresa_producto, login, base, registro_usuario

app_name = 'core'
urlpatterns = [
    path('', home, name="home"),
    path('nosotros/', aboutUs, name="Nuestra Tienda"),
    path('login/', login, name="Inicio de Sesion"),
    path('pago/', carrito, name="Carrito de Compras"),
    path('formulario/', formulario_ingresa_producto, name="Formulario de Productos"),
    path('base/', base, name="Base de Prueba"),
    path('registro/', registro_usuario, name="Registro de Usuario"),

]

emporio/emporio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls')),
]

emporio/core/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Categoria(models.Model):
    categoria = models.CharField(max_length=100, unique=True, verbose_name="Categoría")

    def __str__(self):
        return self.categoria


class Presentacion(models.Model):
    tipoPresentacion = models.CharField(max_length=20, unique=True, verbose_name="Tipo de Presentación")

    def __str__(self):
        return self.tipoPresentacion


class Producto(models.Model):
    codigo = models.IntegerField(unique=True, verbose_name="Código de Producto")
    nombre = models.CharField(max_length=100, verbose_name="Nombre de Producto")
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    contenido = models.CharField(max_length=50, verbose_name="Tipo de Contenido")
    presentacion = models.ForeignKey(Presentacion, on_delete=models.DO_NOTHING)
    precioVenta = models.IntegerField(verbose_name="Precio de Venta a Público")
    foto = models.ImageField(upload_to='img_productos', blank=True, null=True)

    def __str__(self):
        return self.nombre

emporio/core/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Producto
from django.core import validators


class FormularioIngresoProducto(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
#    rep_password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


    # def clean(self):
    #     all_clean_data = super().clean()
    #     password = all_clean_data['password']
    #     rep_password = all_clean_data['repeat_password']
    #
    #     if password != rep_password:
    #         raise forms.ValidationError("¡¡¡Contraseñas no coinciden!!!")

emporio/core/views.py
from django.shortcuts import render
from .models import Producto
from .forms import FormularioIngresoProducto, UserForm


# Create your views here.
def base(request):
    aboutUs_dict = {"insertame": "Este es el template de la página web"}
    return render(request, "core/base.html", context=aboutUs_dict)

def home(request):
    lista_productos = Producto.objects.order_by('codigo')
    producto_dict = {"productos": lista_productos}
    return render(request, "core/home.html", context=producto_dict)

def aboutUs(request):
    aboutUs_dict = {"insertame": "Aquí se describe el local, la dirección y redes sociales"}
    return render(request, "core/aboutus.html", context=aboutUs_dict)

def login(request):
    login_dict = {"insertame": "Aquí inician sesión los trabajadores y clientes de la tienda"}
    return render(request, "core/login.html", context=login_dict)

def carrito(request):
    carrito_dict = {"insertame": "Aquí va el detalle de compras y se formaliza el pago"}
    return render(request, "core/carrito.html", context=carrito_dict)

def formulario_ingresa_producto(request):
    formulario = FormularioIngresoProducto()

    if request.method == "POST":
        formulario = FormularioIngresoProducto(request.POST)

        if formulario.is_valid():
            formulario.save(commit=True)

            if 'foto' in request.FILES:
                formulario.foto = request.FILES['foto']
            formulario.save()
            return home(request)
        else:
            print('ERROR, FORMULARIO INVALIDO')

    return render(request, "core/formulario.html", {'formulario':formulario})

def registro_usuario(request):

    registrado = False

    if request.method == "POST":
        form_usuario = UserForm(data=request.POST)

        if form_usuario.is_valid():
            user = form_usuario.save()
            user.set_password(user.password)
            user.save()
            registrado = True
        else:
            print(form_usuario.errors)
    else:
        form_usuario = UserForm()

    return render(request, 'core/registro.html',{'formulario_usuario':form_usuario, 'registrado':registrado})

emporio/templates/core/aboutus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
</head>
<body>
    <h1>Nuestra Tienda</h1>
    {{ insertame }}
    
</body>
</html>

emporio/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title_block %}
        <!-- Título de Página -->
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/emporioStyles.css' %}">
</head>

<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <!-- Barra de navegación -->
    <nav>
        <div id="barra_navegacion" class="d-flex justify-content-start">
            <div class="container text-center">
                <div id="titulo" class="row align-items-start fs-2 text fw-bold">
                    Bienvenidos al
                </div>
            </div>
        </div>
        <div id="barra_navegacion" class="d-flex justify-content-center">
            <a class="navbar-brand" href="{% url 'core:home' %}">
                <img id="logo_emporio" src="{% static 'images/Logo_Emporio.png' %}" alt="Logo Emporio" width="321"
                    height="118">
            </a>
        </div>
        <div id="barra_navegacion" class="d-flex justify-content-end">
            <ul class="nav nav-tabs fw-bold">
                <li class="nav-item dropdown" value="Catálogo">
                    <a id="navtabs" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                        aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-shop" viewBox="0 0 16 16">
                            <path
                                d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zM4 15h3v-5H4v5zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3zm3 0h-2v3h2v-3z" />
                        </svg>
                    </a>
                    <ul id="navtabs" class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Frutos Secos y Semillas</a></li>
                        <li><a class="dropdown-item" href="#">Sales y Endulzantes</a></li>
                        <li><a class="dropdown-item" href="#">Suplementos y Superalimentos</a></li>
                        <li><a class="dropdown-item" href="#">Harinas, Pan y Pastas</a></li>
                        <li><a class="dropdown-item" href="#">Tes, Mates e Infusiones</a></li>
                        <li><a class="dropdown-item" href="#">Cereales</a></li>
                        <li><a class="dropdown-item" href="#">Aceites Y Vinagres</a></li>
                        <li><a class="dropdown-item" href="#">Veganos</a></li>
                        <li><a class="dropdown-item" href="#">Cacao y Chocolates</a></li>
                        <li><a class="dropdown-item" href="#">Galletas y Snacks</a></li>
                        <li><a class="dropdown-item" href="#">Untables , Salsas y Enlatados</a></li>
                        <li><a class="dropdown-item" href="#">Legumbres</a></li>
                    </ul>
                </li>
                <li class="nav-item" value="Nosotros">
                    <a id="navtabs" class="nav-link active" aria-current="page" href="{% url 'core:Nuestra Tienda' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-info-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path
                                d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                        </svg>
                    </a>
                </li>
                <!-- href="{% url 'core:Inicio de Sesion' %}"> -->
                <li class="nav-item" value="Inicio Sesión">
                    <a id="navtabs" class="nav-link active" aria-current="page"
                        href="{% url 'admin:index' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                            <path fill-rule="evenodd"
                                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
                    </a>
                </li>
                <li class="nav-item" value="Carrito">
                    <a id="navtabs" class="nav-link active" aria-current="page"
                        href="{% url 'core:Carrito de Compras' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-cart-fill" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div id="contenidopagina" class="container">
        {% block body_block %}
        <!-- Contenido de la Página -->
        {% endblock %}
    </div>

    <!-- Inicio Footer -->
    <div class="footer">
        <div class="container-fluid text-center">
            <div class="d-flex justify-content-start">
                <div class="container text-center">
                    <div id="titulo" class="row align-items-start fs-4 text fw-bold">
                        Síguenos en nuestras Redes Sociales:
                    </div>
                </div>
            </div>
        </div>
            <div class="row">
                <div class="col">
                    <a class="nav-link active" aria-current="page" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                            class="bi bi-instagram" viewBox="0 0 16 16">
                            <path
                                d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                        </svg>
                    </a>
                </div>
                <div class="col">
                    <a class="nav-link active" aria-current="page" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                            class="bi bi-facebook" viewBox="0 0 16 16">
                            <path
                                d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                        </svg>
                    </a>
                </div>
                <div class="col">
                    <a class="nav-link active" aria-current="page" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                            class="bi bi-whatsapp" viewBox="0 0 16 16">
                            <path
                                d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" />
                        </svg>
                    </a>
                </div>
            </div>
            <div class="row justify-content-center">
                Las Torres Nte. 278, Quilicura, Región Metropolitana
            </div>
            <div class="row justify-content-center">
                © 2023 Copyright: Emporio el Semillero
            </div>
        </div>
    </div>
    <!-- Fin Footer -->
</body>

</html>

emporio/templates/core/carrito.html
<!DOCTYPE html>
{% extends "core/base.html" %}

{% block head_title_block %}
Carrito
{% endblock %}

{% block body_block %}
    <h1>Carrito de Compras</h1>
    {{ insertame }}
{% endblock %}

emporio/templates/core/formulario.html
<!DOCTYPE html>
{% extends "core/base.html" %}

{% block head_title_block %}
Formulario
{% endblock %}

{% block body_block %}
<h1>Formulario de Productos</h1>
<div class="container">
    <form enctype="multipart/form-data" method="POST">
        {{ formulario.as_p }}
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

emporio/templates/core/home.html
<!DOCTYPE html>
{% extends "core/base.html" %}
{% load static %}
{% block head_title_block %}
Home
{% endblock %}

{% block body_block %}

<!-- Carousel Inicio -->
<div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img_carousel/banner_emporio.png' %}" class="d-block w-100" alt="..." height="400">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img_carousel/organic_products.png' %}" class="d-block w-100" alt="..." height="400">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img_carousel/aceite_coco.png' %}" class="d-block w-100" alt="..." height="400">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<!-- Carousel Fin -->

<h1>Página de Inicio</h1>
<div class="container">
    <a href="/formulario">Acceso a Formulario</a>
</div>
<div>
    <h2>Productos Disponibles:</h2>
    {% if productos %}
    <table>
        <thead>
            <th>Código</th>
            <th>Nombre</th>
            <th>Contenido</th>
            <th>Presentación</th>
            <th>Precio</th>
        </thead>
        {% for prod in productos %}
        <tr>
            <td>{{ prod.codigo }}</td>
            <td>{{ prod.nombre }}</td>
            <td>{{ prod.contenido }}</td>
            <td>{{ prod.presentacion }}</td>
            <td>{{ prod.precioVenta }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>¡¡¡No hay registros!!!</p>
    {% endif %}
</div>


{% endblock %}

emporio/templates/core/login.html
<!DOCTYPE html>
{% extends "core/base.html" %}

{% block head_title_block %}
LogIn
{% endblock %}

{% block body_block %}
<h1>Inicio de Sesión</h1>
{{ insertame }}
{% endblock %}

emporio/templates/core/registro.html
<!DOCTYPE html>
{% extends "core/base.html" %}

{% block head_title_block %}
LogIn
{% endblock %}

{% block body_block %}
<h1>Registro de Usuario</h1>

{% if registrado %}
    <h1>¡¡¡Gracias Por Registrarse!!!</h1>
{% else %}
    <h1>¡¡¡Registrese Aquí!!!</h1>
    <h3>Complete sus datos:</h3>

    <form method="post">
        {% csrf_token %}
        {{ formulario_usuario.as_p }}
        <input type="submit" name="Registrarse" value="Registrarse">
        
    </form>

{% endif %}


{% endblock %}